### ISSUE TITLE
Can not read 'name' property of undefined

### ISSUE THREAD

**Issue by ipselon** [estools/escodegen#273] opened 2015-11-28 18:36 UTC
What is wrong with the following ? Verison 1.7.0 generates valid js code.

```json5
{
    "type": "Program",
    "body": [
        {
            "type": "ExportNamedDeclaration",
            "declaration": null,
            "specifiers": [
                {
                    "type": "ExportSpecifier",
                    "exported": {
                        "type": "Identifier",
                        "name": "fetchGitHubData"
                    },
                    "local": {
                        "type": "Identifier",
                        "name": "fetchGitHubData"
                    }
                }
            ],
            "source": {
                "type": "Literal",
                "value": "./GitHubRepo/GitHubRepoFormActions.js",
                "raw": "'./GitHubRepo/GitHubRepoFormActions.js'"
            }
        }
    ],
    "sourceType": "script",
    "comments": [],
    "errors": []
}
```

**Comment by michaelficarra** [comment] 2015-11-29 00:41
It looks like escodegen is looking for the ExportSpecifier node to have either an `id` or `imported` field with a `name` field. Your ExportSpecifier node has neither of those fields. The estree format lists the fields ExportSpecifier as `exported` and `local`. I'm guessing that escodegen should be looking for `id` or *`exported`* fields?

**Comment by ipselon** [comment] 2015-11-29 07:32
@michaelficarra if so, why 1.7.0 produces valid JS ?

**Comment by michaelficarra** [comment] 2015-11-29 09:05
You can look these things up for yourself, you know. The relevant line in 1.7.0 is

```js
var result = [ (expr.id || expr.local).name ];
```

So it looks like somebody changed it since then. I'm guessing 1.7.0 wouldn't work properly if you exported the binding `as someOtherName`.

**Comment by ipselon** [comment] 2015-11-29 14:30
Yes, I can look at it. But, the matter is in the validity of AST. AST is valid, so, codegen has to produce valid code.

**Comment by michaelficarra** [comment] 2015-11-29 16:56
Yep, nobody is disputing that. You should send a PR that updates that line (and adds tests).

**Comment by ipselon** [comment] 2015-11-29 18:38
Well, let's clarify, one who found a bug in this lib should find where is the root cause of the bug and fix it. Is it right ?

**Comment by michaelficarra** [comment] 2015-11-29 20:15
Anybody can submit a PR. If you don't want to fix it, though, you'll just have to wait until somebody who does want to fix it submits one.

**Comment by ipselon** [comment] 2015-11-29 20:17
Aha, thanks. Just, do not have time to make PR. Thanks.

**Comment by michaelficarra** [comment] 2015-12-04 15:36
Closing as duplicate of #271.

**Closed by michaelficarra** 2015-12-04 15:36 UTC
